-- =============================================================
-- 근육저축 · Supabase 스키마
-- Supabase 대시보드 > SQL Editor 에 통째로 붙여넣고 Run 한 번.
-- 두 번 실행해도 안전하다 (if not exists / on conflict).
-- =============================================================

-- 1. 사람 ---------------------------------------------------------------
create table if not exists public.people (
  id         smallint primary key,
  code       text unique not null,          -- js/data.js 의 PEOPLE 와 맞춘다
  name       text not null,
  email      text unique not null,          -- Supabase Auth 계정 이메일
  color      text not null default '#45B3E0'
);

insert into public.people (id, code, name, email, color) values
  (1, 'euiyeong', '황의영',  'euiyeong@workout.local', '#45B3E0'),
  (2, 'hwikyung', '박휘경',  'hwikyung@workout.local', '#F2B441')
on conflict (id) do update
  set code = excluded.code, name = excluded.name,
      email = excluded.email, color = excluded.color;

-- 2. 운동 세션 -----------------------------------------------------------
-- exercise 는 FK 가 아니라 그냥 text 다. 새 종목 추가 = js/data.js 한 줄 추가로
-- 끝내기 위한 의도적 선택. (CLAUDE.md 3절 참고)
create table if not exists public.workout_logs (
  id           bigint generated by default as identity primary key,
  person_id    smallint not null references public.people(id),
  logged_on    date not null,
  exercise     text not null,
  reps         integer,                     -- 개수 (푸쉬업 등)
  duration_sec integer,                     -- 시간은 언제나 '초'로 저장
  distance_km  numeric(5,2),
  laps         numeric(4,1),                -- 수영 왕복. 편도는 0.5
  note         text,
  source       text not null default 'app', -- 'app' | 'gform'
  created_at   timestamptz not null default now()
);

create index if not exists workout_logs_person_date_idx
  on public.workout_logs (person_id, logged_on desc);
create index if not exists workout_logs_exercise_idx
  on public.workout_logs (exercise, logged_on desc);

-- 3. 하루 단위 기록 (몸무게 · 그날의 메모 · 쉰 날) ------------------------
create table if not exists public.daily_notes (
  id         bigint generated by default as identity primary key,
  person_id  smallint not null references public.people(id),
  logged_on  date not null,
  weight_kg  numeric(4,1),
  note       text,
  is_rest    boolean not null default false,
  source     text not null default 'app',
  created_at timestamptz not null default now(),
  unique (person_id, logged_on)
);

create index if not exists daily_notes_person_date_idx
  on public.daily_notes (person_id, logged_on desc);

-- 4. RLS -----------------------------------------------------------------
-- 부부 둘만 쓰는 앱이고 서로 기록을 보고 대신 입력하는 것도 허용한다.
-- 따라서 '로그인한 사람은 전부 가능, 로그인 안 하면 아무것도 못 함' 한 줄 규칙.
alter table public.people       enable row level security;
alter table public.workout_logs enable row level security;
alter table public.daily_notes  enable row level security;

drop policy if exists "authenticated read people" on public.people;
create policy "authenticated read people"
  on public.people for select to authenticated using (true);

drop policy if exists "authenticated all workout_logs" on public.workout_logs;
create policy "authenticated all workout_logs"
  on public.workout_logs for all to authenticated
  using (true) with check (true);

drop policy if exists "authenticated all daily_notes" on public.daily_notes;
create policy "authenticated all daily_notes"
  on public.daily_notes for all to authenticated
  using (true) with check (true);
